/**
 * Trichella — Report export: PDF (jsPDF), Word (.doc HTML), Markdown
 */
import { jsPDF } from "jspdf";

const BRAND_GREEN = [31, 92, 58];
const DARK_GREEN  = [14, 47, 31];

/** overallScore = condition burden / severity (higher = worse). Matches App.jsx thresholds. */
function severityHex(score) {
  const s = score ?? 0;
  if (s <= 25) return "#1F5C3A";
  if (s <= 64) return "#7D6B2A";
  return "#B45454";
}

function severityRgb(score) {
  const s = score ?? 0;
  if (s <= 25) return [60, 122, 78];
  if (s <= 64) return [140, 110, 40];
  return [180, 84, 84];
}

function fmtDate(iso) {
  try {
    return new Date(iso).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });
  } catch (_) { return iso || ""; }
}

// ─── MARKDOWN ────────────────────────────────────────────────────────────────
export function buildMarkdown(scan) {
  const { report: r, date, note, accuracy, id } = scan;
  if (!r) return "";
  const lines = [
    `# Trichella — Clinical Scalp Analysis Report`,
    ``,
    `**Date:** ${fmtDate(date)}  `,
    `**Report ID:** ${id || "—"}  `,
    `**Condition burden (0–100, higher = more severe):** ${r.overallScore ?? "—"}/100  `,
    `**Primary Condition:** ${r.primaryCondition ?? "—"}  `,
    `**Urgency:** ${(r.urgency ?? "—").toUpperCase()}`,
    r.urgencyReason ? `> ${r.urgencyReason}` : "",
    ``,
    `---`,
    `## Patient Summary`,
    ``,
    r.patientSummary ?? r.summary ?? "",
    ``,
    `---`,
    `## Clinical Summary`,
    ``,
    r.summary ?? "",
    ``,
    `---`,
    `## Scalp Metrics`,
    ``,
    `| Metric            | Value                     |`,
    `|-------------------|---------------------------|`,
    `| Density           | ${r.metrics?.density ?? "—"}         |`,
    `| Sebum Level       | ${r.metrics?.sebumLevel ?? "—"}      |`,
    `| Hydration         | ${r.metrics?.hydration ?? "—"}       |`,
    `| Inflammation      | ${r.metrics?.inflammation ?? "—"}    |`,
    `| Follicle Health   | ${r.metrics?.follicleHealth ?? "—"}  |`,
    `| Scalp Type        | ${r.metrics?.scalpType ?? "—"}       |`,
    ``,
    `---`,
    `## Detected Conditions`,
    ``,
    ...(r.conditions ?? []).map((c) => `- **${c}**`),
    ``,
    `---`,
    `## Clinical Findings`,
    ``,
    ...(r.findings ?? []).map((f, i) => `${i + 1}. ${f}`),
    ``,
    `---`,
    `## Recommendations`,
    ``,
    ...(r.recommendations ?? []).flatMap((rec) => [
      `### ${rec.title}`,
      `*Priority: ${rec.priority}*`,
      ``,
      rec.detail,
      ``,
    ]),
    `---`,
    `## Next Scan`,
    ``,
    `Recommended follow-up scan in **${r.nextScanDays ?? 30} days**.`,
    ``,
  ];
  if (note?.trim()) lines.push(`---`, `## Additional Notes`, ``, note.trim(), ``);
  if (accuracy) lines.push(`---`, `## Diagnostic Accuracy Feedback`, ``, `Clinician rated this diagnosis as: **${accuracy}**`, ``);
  lines.push(`---`, ``, `*Generated by Trichella — AI Scalp Diagnostics*`);
  return lines.filter((l) => l !== undefined).join("\n");
}

export function downloadMarkdown(scan) {
  const md = buildMarkdown(scan);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Trichella_Report_${scan.id || Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── WORD (.doc — HTML-based, opens in Word/LibreOffice) ────────────────────
export function downloadWord(scan) {
  const { report: r, date, note, accuracy, id } = scan;
  if (!r) return "";
  const d = fmtDate(date);
  const pc = { High: "#B45454", Medium: "#2F6E44", Low: "#809486" };

  const metricRows = [
    ["Density", r.metrics?.density],
    ["Sebum Level", r.metrics?.sebumLevel],
    ["Hydration", r.metrics?.hydration],
    ["Inflammation", r.metrics?.inflammation],
    ["Follicle Health", r.metrics?.follicleHealth],
    ["Scalp Type", r.metrics?.scalpType],
  ].map(([l, v]) => `<tr><td style="padding:7px 12px;border:1px solid #D4E3D9;color:#4C6254;font-weight:600;">${l}</td><td style="padding:7px 12px;border:1px solid #D4E3D9;font-weight:700;">${v ?? "—"}</td></tr>`).join("");

  const findingItems = (r.findings ?? []).map((f, i) => `<p style="margin:5px 0 5px 4px;font-size:13px;"><span style="color:#1F5C3A;font-weight:700;">${i + 1}.</span> ${f}</p>`).join("");

  const recRows = (r.recommendations ?? []).map((rec) =>
    `<tr><td style="padding:10px 12px;border:1px solid #D4E3D9;font-weight:700;vertical-align:top;width:130px;">${rec.title ?? ""}</td><td style="padding:10px 12px;border:1px solid #D4E3D9;font-size:13px;vertical-align:top;">${rec.detail ?? ""}</td><td style="padding:10px 12px;border:1px solid #D4E3D9;text-align:center;font-weight:800;color:${pc[rec.priority] ?? "#333"};vertical-align:top;width:70px;">${rec.priority ?? ""}</td></tr>`
  ).join("");

  const urgencyBg = { routine: "#2F6E44", monitor: "#7D6B2A", consult: "#B45454" };
  const ub = urgencyBg[r.urgency] ?? "#2F6E44";

  const scoreColor = severityHex(r.overallScore);

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="UTF-8">
<style>
  body{font-family:Calibri,Arial,sans-serif;color:#102018;margin:0;padding:0}
  .header{background:#0E2F1F;padding:32px 40px 20px;color:#F3F7F5}
  .header h1{font-family:Georgia,serif;font-size:28px;margin:0 0 4px;color:#F3F7F5}
  .header .sub{font-size:12px;color:#B6CBC0;margin-top:4px}
  .body{padding:32px 40px}
  h2{font-family:Georgia,serif;font-size:16px;color:#1F5C3A;margin:28px 0 10px;border-bottom:2px solid #D4E3D9;padding-bottom:6px}
  .meta{font-size:13px;color:#4C6254;margin:4px 0}
  .score{display:inline-block;font-size:32px;font-weight:800;color:${scoreColor}}
  .badge{display:inline-block;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:700;color:#fff}
  .summary{background:#ECF3EE;border-left:4px solid #1F5C3A;padding:14px 18px;margin:12px 0;font-size:14px;line-height:1.7;border-radius:0 8px 8px 0}
  .patient-summary{background:#F5FAF7;border:1px solid #D4E3D9;padding:12px 16px;margin:12px 0;font-size:14px;border-radius:8px;color:#1F5C3A;font-style:italic}
  table{width:100%;border-collapse:collapse;margin:12px 0;font-size:13px}
  th{background:#1F5C3A;color:#fff;padding:9px 12px;text-align:left;font-size:12px}
  .cond{display:inline-block;background:#ECF3EE;border:1px solid #D4E3D9;border-radius:20px;padding:4px 12px;margin:3px;font-size:13px;font-weight:600;color:#1F5C3A}
  .footer{margin-top:40px;padding-top:14px;border-top:1px solid #D4E3D9;font-size:11px;color:#809486}
</style></head>
<body>
<div class="header">
  <h1>Trichella — Clinical Scalp Analysis Report</h1>
  <div class="sub">Generated: ${d} &nbsp;|&nbsp; Report ID: ${id || "—"}</div>
</div>
<div class="body">
  <div style="display:flex;align-items:flex-start;gap:32px;flex-wrap:wrap;margin-bottom:8px">
    <div>
      <p class="meta"><strong>Overall Score</strong></p>
      <div class="score">${r.overallScore ?? "—"}<span style="font-size:16px;font-weight:400;color:#809486">/100</span></div>
    </div>
    <div>
      <p class="meta"><strong>Primary Condition</strong></p>
      <p style="font-size:16px;font-weight:700;color:#1F5C3A;margin:4px 0">${r.primaryCondition ?? "—"}</p>
    </div>
    <div>
      <p class="meta"><strong>Urgency</strong></p>
      <span class="badge" style="background:${ub}">${(r.urgency ?? "").toUpperCase()}</span>
      ${r.urgencyReason ? `<p style="font-size:12px;color:#4C6254;margin:4px 0;max-width:240px">${r.urgencyReason}</p>` : ""}
    </div>
  </div>

  ${r.patientSummary ? `<div class="patient-summary">"${r.patientSummary}"</div>` : ""}

  <h2>Clinical Summary</h2>
  <div class="summary">${r.summary ?? ""}</div>

  <h2>Scalp Metrics</h2>
  <table><tr><th>Metric</th><th>Value</th></tr>${metricRows}</table>

  <h2>Detected Conditions</h2>
  <p>${(r.conditions ?? []).map((c) => `<span class="cond">${c}</span>`).join(" ")}</p>

  <h2>Clinical Findings</h2>
  ${findingItems}

  <h2>Recommendations</h2>
  <table>
    <tr><th>Treatment</th><th>Clinical Guidance</th><th style="width:70px;text-align:center">Priority</th></tr>
    ${recRows}
  </table>

  <h2>Next Recommended Scan</h2>
  <p style="font-size:14px">Follow-up scan recommended in <strong>${r.nextScanDays ?? 30} days</strong>.</p>

  ${note?.trim() ? `<h2>Additional Notes</h2><p style="font-size:14px">${note.trim()}</p>` : ""}
  ${accuracy ? `<h2>Diagnostic Accuracy Feedback</h2><p style="font-size:14px">Clinician rated diagnosis as: <strong>${accuracy}</strong></p>` : ""}

  <div class="footer">Generated by Trichella — AI Scalp Diagnostics &nbsp;|&nbsp; Report ID: ${id || "—"}</div>
</div>
</body></html>`;

  const blob = new Blob(["\ufeff", html], { type: "application/msword;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Trichella_Report_${scan.id || Date.now()}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── PDF (jsPDF) ─────────────────────────────────────────────────────────────
export async function downloadPDF(scan) {
  const { report: r, date, note, accuracy, id, preview } = scan;
  if (!r) return;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const MARGIN = 18;
  const CW = W - MARGIN * 2;
  let y = 0;

  const newPage = () => {
    doc.addPage();
    y = MARGIN;
    doc.setFillColor(...BRAND_GREEN);
    doc.rect(0, 0, W, 8, "F");
    doc.setFontSize(7.5);
    doc.setTextColor(220, 240, 230);
    doc.text("Trichella — Clinical Scalp Analysis Report", MARGIN, 5.8);
    doc.setTextColor(150, 195, 170);
    doc.text(`Report ID: ${id || "—"}`, W - MARGIN, 5.8, { align: "right" });
    y = 16;
  };

  const checkY = (need) => { if (y + need > 272) { newPage(); return true; } return false; };

  const sectionHeading = (txt) => {
    checkY(14);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_GREEN);
    doc.text(txt, MARGIN, y);
    doc.setDrawColor(...BRAND_GREEN);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, y + 2, MARGIN + CW, y + 2);
    y += 8;
  };

  // ── Cover header ──────────────────────────────────────────────────────────
  doc.setFillColor(...DARK_GREEN);
  doc.rect(0, 0, W, 48, "F");
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 48, W, 2.5, "F");

  // Logo pill
  doc.setFillColor(240, 250, 245);
  doc.roundedRect(MARGIN, 11, 20, 20, 4, 4, "F");
  doc.setFontSize(14);
  doc.setTextColor(31, 92, 58);
  doc.text("T", MARGIN + 7.5, 24.5);

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(240, 250, 245);
  doc.text("Trichella", MARGIN + 25, 22);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(170, 210, 190);
  doc.text("Clinical Scalp Analysis Report", MARGIN + 25, 29);
  doc.text(`Date: ${fmtDate(date)}   |   Report ID: ${id || "—"}`, MARGIN + 25, 36);

  // Score circle (top-right of header)
  const scoreVal = r.overallScore ?? 0;
  const scoreC = severityRgb(scoreVal);
  const cx = W - MARGIN - 18; const cy = 24;
  doc.setFillColor(255, 255, 255, 30);
  doc.circle(cx, cy, 15, "F");
  doc.setFillColor(...scoreC);
  doc.circle(cx, cy, 14, "F");
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(`${r.overallScore ?? "—"}`, cx, cy + 2, { align: "center" });
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(220, 240, 230);
  doc.text("/100", cx, cy + 8, { align: "center" });

  y = 56;

  // Scan preview (if available)
  if (preview && preview.startsWith("data:image")) {
    try {
      const imgFmt = preview.includes("data:image/png") ? "PNG" : "JPEG";
      doc.addImage(preview, imgFmt, MARGIN, y, 28, 28);
      // Primary + urgency badges alongside image
      const bx = MARGIN + 32;
      doc.setFillColor(...BRAND_GREEN);
      doc.roundedRect(bx, y + 2, CW - 32, 11, 3, 3, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(240, 250, 245);
      doc.text(`Primary: ${r.primaryCondition ?? "—"}`, bx + 5, y + 9);

      const urgBg = r.urgency === "consult" ? [180, 84, 84] : r.urgency === "monitor" ? [140, 110, 40] : [60, 122, 78];
      doc.setFillColor(...urgBg);
      doc.roundedRect(bx, y + 16, CW - 32, 10, 3, 3, "F");
      doc.setFontSize(8.5);
      doc.setTextColor(240, 250, 245);
      doc.text(`Urgency: ${(r.urgency ?? "").toUpperCase()}${r.urgencyReason ? "  —  " + r.urgencyReason.slice(0, 65) : ""}`, bx + 5, y + 22.5);
      y += 36;
    } catch (_) { y += 4; }
  } else {
    // No preview — just badges
    doc.setFillColor(...BRAND_GREEN);
    doc.roundedRect(MARGIN, y, CW * 0.52, 11, 3, 3, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(240, 250, 245);
    doc.text(`Primary: ${r.primaryCondition ?? "—"}`, MARGIN + 4, y + 7.5);

    const urgBg = r.urgency === "consult" ? [180, 84, 84] : r.urgency === "monitor" ? [140, 110, 40] : [60, 122, 78];
    doc.setFillColor(...urgBg);
    doc.roundedRect(MARGIN + CW * 0.55, y, CW * 0.45, 11, 3, 3, "F");
    doc.setTextColor(240, 250, 245);
    doc.text(`Urgency: ${(r.urgency ?? "").toUpperCase()}`, MARGIN + CW * 0.55 + 4, y + 7.5);
    y += 18;
  }

  // Patient summary pill
  if (r.patientSummary) {
    checkY(18);
    doc.setFillColor(236, 243, 238);
    const psLines = doc.splitTextToSize(`"${r.patientSummary}"`, CW - 10);
    doc.roundedRect(MARGIN, y, CW, psLines.length * 5.5 + 10, 4, 4, "F");
    doc.setFillColor(...BRAND_GREEN);
    doc.rect(MARGIN, y, 3, psLines.length * 5.5 + 10, "F");
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(31, 92, 58);
    doc.text(psLines, MARGIN + 7, y + 7);
    y += psLines.length * 5.5 + 15;
  }

  // ── Clinical Summary ──────────────────────────────────────────────────────
  sectionHeading("Clinical Summary");
  const sumLines = doc.splitTextToSize(r.summary ?? "", CW - 6);
  checkY(sumLines.length * 5.5 + 10);
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(26, 46, 32);
  doc.text(sumLines, MARGIN, y);
  y += sumLines.length * 5.5 + 10;

  // ── Metrics grid ─────────────────────────────────────────────────────────
  sectionHeading("Scalp Metrics");
  const metrics = [
    ["Density", r.metrics?.density],
    ["Sebum Level", r.metrics?.sebumLevel],
    ["Hydration", r.metrics?.hydration],
    ["Inflammation", r.metrics?.inflammation],
    ["Follicle Health", r.metrics?.follicleHealth],
    ["Scalp Type", r.metrics?.scalpType],
  ];
  const colW = CW / 3;
  checkY(44);
  metrics.forEach(([label, value], i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const mx = MARGIN + col * colW;
    const my = y + row * 18;
    doc.setFillColor(245, 250, 247);
    doc.roundedRect(mx, my, colW - 2.5, 14, 3, 3, "F");
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 140, 115);
    doc.text(label.toUpperCase(), mx + 4, my + 5.5);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 46, 32);
    doc.text(value ?? "—", mx + 4, my + 11.5);
  });
  y += Math.ceil(metrics.length / 3) * 18 + 8;

  // ── Conditions ────────────────────────────────────────────────────────────
  sectionHeading("Detected Conditions");
  checkY(14);
  let cx2 = MARGIN;
  (r.conditions ?? []).forEach((cond) => {
    const tw = doc.getTextWidth(cond) + 10;
    if (cx2 + tw > MARGIN + CW) { cx2 = MARGIN; y += 9; }
    doc.setFillColor(236, 243, 238);
    doc.roundedRect(cx2, y - 5, tw, 8, 2, 2, "F");
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_GREEN);
    doc.text(cond, cx2 + 5, y + 0.5);
    cx2 += tw + 4;
  });
  y += 14;

  // ── Clinical Findings ─────────────────────────────────────────────────────
  sectionHeading("Clinical Findings");
  (r.findings ?? []).forEach((f, i) => {
    const lines = doc.splitTextToSize(`${i + 1}.  ${f}`, CW - 4);
    checkY(lines.length * 5 + 4);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(26, 46, 32);
    doc.text(lines, MARGIN + 2, y);
    y += lines.length * 5 + 4;
  });
  y += 4;

  // ── Recommendations ───────────────────────────────────────────────────────
  sectionHeading("Recommendations");
  const priorityColors = { High: [180, 84, 84], Medium: [47, 110, 68], Low: [129, 152, 138] };
  (r.recommendations ?? []).forEach((rec) => {
    const detLines = doc.splitTextToSize(rec.detail ?? "", CW - 48);
    const blockH = detLines.length * 5.2 + 20;
    checkY(blockH + 4);

    doc.setFillColor(245, 250, 247);
    doc.roundedRect(MARGIN, y, CW, blockH, 4, 4, "F");
    doc.setFillColor(...BRAND_GREEN);
    doc.rect(MARGIN, y, 3, blockH, "F");

    const pc2 = priorityColors[rec.priority] ?? priorityColors.Medium;
    doc.setFillColor(...pc2);
    doc.roundedRect(MARGIN + CW - 34, y + 4, 30, 8, 3, 3, "F");
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text((rec.priority ?? "").toUpperCase(), MARGIN + CW - 19, y + 9.5, { align: "center" });

    doc.setFontSize(9.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(31, 92, 58);
    doc.text(rec.title ?? "", MARGIN + 7, y + 11);

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(26, 46, 32);
    doc.text(detLines, MARGIN + 7, y + 18);

    y += blockH + 5;
  });

  // ── Next scan banner ──────────────────────────────────────────────────────
  checkY(18);
  doc.setFillColor(...DARK_GREEN);
  doc.roundedRect(MARGIN, y, CW, 12, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 235, 215);
  doc.text(`Next recommended scan: in ${r.nextScanDays ?? 30} days`, MARGIN + 5, y + 8);
  y += 18;

  // ── Notes ─────────────────────────────────────────────────────────────────
  if (note?.trim()) {
    sectionHeading("Additional Notes");
    const noteLines = doc.splitTextToSize(note.trim(), CW);
    checkY(noteLines.length * 5 + 6);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(26, 46, 32);
    doc.text(noteLines, MARGIN, y);
    y += noteLines.length * 5 + 8;
  }

  // ── Accuracy ──────────────────────────────────────────────────────────────
  if (accuracy) {
    checkY(12);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 140, 115);
    doc.text(`Diagnostic accuracy feedback: ${accuracy}`, MARGIN, y);
    y += 10;
  }

  // ── Footer on every page ──────────────────────────────────────────────────
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(129, 152, 138);
    doc.text(`Trichella — AI Scalp Diagnostics  |  Report ID: ${id || "—"}  |  Page ${p} / ${pages}`, MARGIN, 292);
  }

  doc.save(`Trichella_Report_${scan.id || Date.now()}.pdf`);
}
